### PR TITLE
Add support for creating single files

### PR DESCRIPTION
**Pull request by ColinDuquesnoy**
Now boss is able to add a single file from template to an existing project.

File templates are made up of two files:
  - the template
  - the config file which must have the same base name as the template file.

Single file templates live next to the templates directories. E.g.:

- module.py
- module.yml
- python
- cement-app
- ...

I added a test case for this.

Let me know what you think or if there is anything to change!

### CODE REVIEW

**Comment by derks** [comment]
Standard templates (dirs) **can** be used to add files to an existing directory/project.  For example:

```
my-template/
my-template/boss.yml
my-template/some-file.txt
```

Using this template (just a generic  example)...  and:

```
$ boss create -t my-repo:my-template /path/to/existing/project
```


You'd end up with `/path/to/existing/project/some-file.txt` regardless of what files already exist in that destination path.  Therefore, I don't see the purpose of this patch/pull.

Thoughts?

**Comment by ColinDuquesnoy** [comment]
Yes, this is fine if you use boss directly for your own usage but I wanted to try to use boss from within an IDE to manage the project/file templates. If everything is in a standard template (dirs), how can I make the distinction between a project template and a single file template?

**Comment by derks** [comment]
Hrm. I guess I don't follow.  The difference between a single file, and a project directory is a moot point... you end up with `/path/to/existing/project/some-file.txt` either way.  Or am I missing something.

Not trying to be rude, just not quite connecting in my brain on how/why the current process wouldn't work.

Thanks for taking the time to clarify!

**Comment by ColinDuquesnoy** [comment]
> Not trying to be rude, just not quite connecting in my brain on how/why the current process wouldn't work.

You're right, the current process would work. This is a presentation issue.

I have two possible actions: create a new project from template or add a file from template to an existing project. I need to show a different set of templates depending on the action chosen by the user. Creating a new project will open a new project window while adding a new file will just create a new file in the current project tree and open a new editor tab.

**Comment by derks** [comment]
Could this use case be made possible by adding a unique configuration setting to the `boss.yml` in each of the template dirs to differentiate them as a) a project template directory, or b) a template file.  Thinking something like:

**my-project/boss.yml**
```yaml
some_unique_key:
    type: project
variables:
    foo: bar
```

**my-project-file-addon/boss.yml**
```yaml
some_unique_key:
    type: project_file_addon
variables:
    foo: bar
```

You'd basically just need a wrapper around BOSS to read the `boss.yml`, determine what type of template it is, and then act accordingly.  

Thoughts?

**Comment by ColinDuquesnoy** [comment]
Good idea! I'll give it a try during this weekend and will let you know how it went.

To integrate boss with the IDE I also need a way to use it as a module. I have a patch where I made a bunch of API function that wraps the cli commands. I had to modify some internal function to include a callback to customize the way boss asks for answers. If you're interested I can submit a PR and talk about it.

**Comment by ColinDuquesnoy** [comment]
Works for me. I feel stupid I haven't though about it myself....

Thank you very much for your help and for your work on boss. This is really a great project!

**Comment by derks** [comment]
@ColinDuquesnoy really glad that worked out.  Don't feel back, the `boss.yml` config is only documented for the purposes of BOSS... it was just the first thing I thought of (rather than making code changes.. just expanding the config).

I have some ideas for new features that will make customizing like this easier (or atleast, better documented)... so to that extent, thank you for the contribution!

**Pull request closed without merging**
